name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./update-gh-pages
        env:
          DEPLOY_TOKEN: ${{ secrets.GH_PAGES_DEPLOY }}
